FROM java

LABEL maintainer "liang_xiao@hoperun.com"

COPY /project/target/demo01-0.0.1-SNAPSHOT.jar  /usr/src/myapp/demo01-0.0.1-SNAPSHOT.jar

WORKDIR /usr/src/myapp/

ENTRYPOINT java -jar demo01-0.0.1-SNAPSHOT.jar